import type { Metadata } from "next";
import { Raleway, Cormorant_Infant } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/fragments/navbar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const bodoniModa = Cormorant_Infant({
  variable: "--font-bodoni-moda",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${bodoniModa.variable} antialiased bg-bgPrimary`}
      >
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
